sip:
  username: "T2VJvgg2VG9"
  password: "v6b34t6VpUH"
  domain: "infinitum.3cx.com.au"
  port: 5060
  tls_enabled: false

ai:
  openai_key: "your_openai_key"
  elevenlabs_key: "your_elevenlabs_key"

audio:
  tts_voice: "Adam"