version: '3'
services:
  sip-bot:
    build: .
    container_name: sip-bot
    restart: always
    network_mode: "host"  # Needed for SIP
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - SIP_USERNAME=${SIP_USERNAME:-T2VJvgg2VG9}
      - SIP_PASSWORD=${SIP_PASSWORD:-v6b34t6VpUH}
      - SIP_DOMAIN=${SIP_DOMAIN:-infinitum.3cx.com.au}
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    devices:
      - "/dev/snd:/dev/snd"  # Pass audio devices
