version: "3.8"

services:
  ai-voice-bot:
    build: .
    container_name: ai-voice-bot
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - SIP_USERNAME=${SIP_USERNAME}
      - SIP_PASSWORD=${SIP_PASSWORD}
      - SIP_DOMAIN=${SIP_DOMAIN}
    volumes:
      - ./logs:/app/logs
      - /tmp/baresip.sock:/tmp/baresip.sock